Fix panic on IRC reactor prepare
Running using the following config:

    [features]
    report_metadata = true
    report_mime = true
    mask_highlights = true
    send_notice = true
    url_limit = 4

Caused the panic:

    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidConfig { path: "/home/ed/Projects/url-bot/config-nom.toml", cause: ServerNotSpecified }', libcore/result.rs:945:5
    stack backtrace:
       0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
                 at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
       1: std::sys_common::backtrace::print
                 at libstd/sys_common/backtrace.rs:71
                 at libstd/sys_common/backtrace.rs:59
       2: std::panicking::default_hook::{{closure}}
                 at libstd/panicking.rs:211
       3: std::panicking::default_hook
                 at libstd/panicking.rs:227
       4: std::panicking::rust_panic_with_hook
                 at libstd/panicking.rs:475
       5: std::panicking::continue_panic_fmt
                 at libstd/panicking.rs:390
       6: rust_begin_unwind
                 at libstd/panicking.rs:325
       7: core::panicking::panic_fmt
                 at libcore/panicking.rs:77
       8: core::result::unwrap_failed
                 at /checkout/src/libcore/macros.rs:26
       9: <core::result::Result<T, E>>::unwrap
                 at /checkout/src/libcore/result.rs:782
      10: url_bot::main
                 at src/main.rs:96
      11: std::rt::lang_start::{{closure}}
                 at /checkout/src/libstd/rt.rs:74
      12: std::panicking::try::do_call
                 at libstd/rt.rs:59
                 at libstd/panicking.rs:310
      13: __rust_maybe_catch_panic
                 at libpanic_unwind/lib.rs:105
      14: std::rt::lang_start_internal
                 at libstd/panicking.rs:289
                 at libstd/panic.rs:392
                 at libstd/rt.rs:58
      15: std::rt::lang_start
                 at /checkout/src/libstd/rt.rs:74
      16: main
      17: __libc_start_main
      18: _start

Now we have:

    IRC prepare error: invalid config: /home/ed/Projects/url-bot/config-nom.toml