Don't panic on IRC reactor errors
Gracefully handle the error, and produce a message.

This:

    Using in-memory database
    Using configuration at: ./config.toml
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoUsableNick', libcore/result.rs:945:5
    note: Run with `RUST_BACKTRACE=1` for a backtrace.

...is replaced with this:

    Using in-memory database
    Using configuration at: ./config.toml
    IRC client error: none of the specified nicknames were usable

Much better ;)